// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDMKwQil8Su9AXKd9X-xPqZL07i2XaUU',
    appId: '1:898204568740:web:529a574504fedd7041aa31',
    messagingSenderId: '898204568740',
    projectId: 'alphatrekk-b2721',
    authDomain: 'alphatrekk-b2721.firebaseapp.com',
    storageBucket: 'alphatrekk-b2721.firebasestorage.app',
    measurementId: 'G-LNSKC5XG62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRiXqik7GYAP7yAiCmvRUPxumx4lsqoo',
    appId: '1:898204568740:android:88b3e1f8f9d903bd41aa31',
    messagingSenderId: '898204568740',
    projectId: 'alphatrekk-b2721',
    storageBucket: 'alphatrekk-b2721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgx-XidHNbNn8SqID_bljVLTJmTgXLEM',
    appId: '1:898204568740:ios:0569e9e170e407ce41aa31',
    messagingSenderId: '898204568740',
    projectId: 'alphatrekk-b2721',
    storageBucket: 'alphatrekk-b2721.firebasestorage.app',
    iosClientId: '898204568740-99o3mqia0bje1ucdqtv55mv5fjsnfh1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaTreck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgx-XidHNbNn8SqID_bljVLTJmTgXLEM',
    appId: '1:898204568740:ios:0569e9e170e407ce41aa31',
    messagingSenderId: '898204568740',
    projectId: 'alphatrekk-b2721',
    storageBucket: 'alphatrekk-b2721.firebasestorage.app',
    iosClientId: '898204568740-99o3mqia0bje1ucdqtv55mv5fjsnfh1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaTreck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYDMKwQil8Su9AXKd9X-xPqZL07i2XaUU',
    appId: '1:898204568740:web:8ba7df7d7a930e9b41aa31',
    messagingSenderId: '898204568740',
    projectId: 'alphatrekk-b2721',
    authDomain: 'alphatrekk-b2721.firebaseapp.com',
    storageBucket: 'alphatrekk-b2721.firebasestorage.app',
    measurementId: 'G-H0B53D2706',
  );
}
